#!/bin/bash

# Test script for fallback error mechanism
# This script tests the etcd client's fallback error handling

NODE_ID=""
USER_ID="user001"

echo "=== Etcd Client Fallback Error Mechanism Test ==="
echo ""

# Allow specifying etcd endpoint via ETCD_CONTAINER_NAME env var or first argument
# Usage examples:
#   ETCD_CONTAINER_NAME="test-etcd-container" ./test_fallback_error.sh
#   ./test_fallback_error.sh test-etcd-container
if [ -n "$1" ]; then
  ETCD_CONTAINER_NAME="$1"
fi

# Build etcdctl invocation with optional --endpoints flag
if [ -n "$ETCD_CONTAINER_NAME" ]; then
  ETCDCTL_CMD="docker exec "$ETCD_CONTAINER_NAME" /usr/local/bin/etcdctl"
else
  ETCDCTL_CMD="/usr/local/bin/etcdctl"
fi

# Check if etcd is running
if ! $ETCDCTL_CMD endpoint health &>/dev/null; then
  echo "ERROR: etcd is not running or not reachable at endpoint: ${ETCD_CONTAINER_NAME:-(default)}. Please start an etcd instance."
  exit 1
fi

echo "✓ Etcd is running"
echo ""

# Discover node UUID generated by running fastrg process.
# Strategy: allow user to set OPENRG_NODE_UUID env var, else try to find a node id
# from existing etcd keys under configs/{node_uuid}/hsi/. If none found, fall back
# to a default test id and warn the user.
if [ -n "$OPENRG_NODE_UUID" ]; then
  NODE_ID="$OPENRG_NODE_UUID"
else
  FIRST_KEY=$($ETCDCTL_CMD get configs/ --prefix --keys-only 2>/dev/null | grep -m1 '^configs/' || true)
  if [ -n "$FIRST_KEY" ]; then
    # Extract the node uuid between configs/ and /hsi
    NODE_ID=$(echo "$FIRST_KEY" | sed -n 's#configs/\([^/]*\)/hsi/.*#\1#p')
  fi
fi

if [ -z "$NODE_ID" ]; then
  echo "WARNING: Could not auto-detect FastRG node UUID from etcd. Using fallback node id 'test-node-12345'."
  NODE_ID="test-node-12345"
else
  echo "Detected FastRG node UUID: $NODE_ID"
fi

# Clean up previous test data
echo "Cleaning up previous test data..."
$ETCDCTL_CMD del configs/ --prefix
$ETCDCTL_CMD del commands/ --prefix
$ETCDCTL_CMD del failed_events/ --prefix
echo "✓ Cleanup complete"
echo ""

# Test 1: Valid HSI config (should succeed)
echo "=== Test 1: Valid HSI Config ==="
VALID_CONFIG='{
  "user_id": "user001",
  "vlan_id": "100",
  "account_name": "test@isp.com",
  "password": "pass123",
  "dhcp_addr_pool": "192.168.1.100-192.168.1.200",
  "dhcp_subnet": "192.168.1.0/24",
  "dhcp_gateway": "192.168.1.1"
}'

${ETCDCTL_CMD} put "configs/$NODE_ID/hsi/$USER_ID" "$VALID_CONFIG"
echo "✓ Written valid HSI config"
sleep 2

echo ""
echo "=== Test 2: Invalid JSON (should create failed_event) ==="
INVALID_JSON='{"user_id": "user002", "vlan_id": "200"'  # Missing closing brace

${ETCDCTL_CMD} put "configs/$NODE_ID/hsi/user002" "$INVALID_JSON"
echo "✓ Written invalid JSON"
sleep 2

# Check for failed_events
echo ""
echo "Checking for failed_events..."
FAILED_EVENTS=$(${ETCDCTL_CMD} get failed_events/ --prefix --keys-only | wc -l)
if [ "$FAILED_EVENTS" -gt 0 ]; then
    echo "✓ Found $FAILED_EVENTS failed_events"
    echo ""
    echo "Failed event details:"
  ${ETCDCTL_CMD} get failed_events/ --prefix
else
    echo "⚠ No failed_events found (this might be OK if callback succeeded despite invalid JSON)"
fi

echo ""
echo "=== Test 3: Missing Required Fields ==="
INCOMPLETE_CONFIG='{
  "user_id": "user003",
  "vlan_id": "300"
}'

${ETCDCTL_CMD} put "configs/$NODE_ID/hsi/user003" "$INCOMPLETE_CONFIG"
echo "✓ Written incomplete config"
sleep 2

echo ""
echo "=== Test 4: Invalid Key Format ==="
${ETCDCTL_CMD} put "configs/hsi/invalid_format" '{"test": "data"}'
echo "✓ Written with invalid key format"
sleep 2

echo ""
echo "=== Test 5: PPPoE Command ==="
PPPOE_COMMAND='{
  "action": "dial",
  "user_id": "user001",
  "vlan": "100",
  "account": "test@isp.com",
  "password": "pass123",
  "timestamp": 1698912345
}'

${ETCDCTL_CMD} put "commands/$NODE_ID/pppoe_dial_user001" "$PPPOE_COMMAND"
echo "✓ Written PPPoE command"
sleep 2

echo ""
echo "=== Test 6: DELETE Event ==="
${ETCDCTL_CMD} del "configs/$NODE_ID/hsi/$USER_ID"
echo "✓ Deleted HSI config"
sleep 2

echo ""
echo "=== Summary of Failed Events ==="
echo ""
echo "Total failed_events:"
${ETCDCTL_CMD} get failed_events/ --prefix --keys-only | wc -l

echo ""
echo "Failed events by type:"
echo "  HSI Config errors:"
${ETCDCTL_CMD} get failed_events/hsi_config/ --prefix --keys-only | wc -l
echo "  PPPoE Command errors:"
${ETCDCTL_CMD} get failed_events/pppoe_command/ --prefix --keys-only | wc -l

echo ""
echo "=== Detailed Failed Events ==="
${ETCDCTL_CMD} get failed_events/ --prefix | while read -r key; do
    if [[ $key == failed_events/* ]]; then
        echo ""
        echo "Key: $key"
        read -r value
        echo "$value" | python3 -m json.tool 2>/dev/null || echo "$value"
    fi
done

echo ""
echo "Cleaning up test data..."
$ETCDCTL_CMD del configs/ --prefix
$ETCDCTL_CMD del commands/ --prefix
$ETCDCTL_CMD del failed_events/ --prefix
echo "✓ Cleanup complete"

echo ""
echo "=== Test Commands for Manual Testing ==="
echo ""
echo "# Watch all events in real-time:"
echo "etcdctl watch configs/$NODE_ID/ --prefix"
echo "etcdctl watch failed_events/ --prefix"
echo ""
echo "# Clean up test data:"
echo "etcdctl del configs/ --prefix"
echo "etcdctl del commands/ --prefix"
echo "etcdctl del failed_events/ --prefix"
echo ""
echo "# Create test config that should succeed:"
echo "etcdctl put configs/$NODE_ID/hsi/$USER_ID '$VALID_CONFIG'"
echo ""
echo "# Create test config that should fail (invalid JSON):"
echo "etcdctl put configs/$NODE_ID/hsi/user999 '{invalid json'"
echo ""

echo "=== Test Complete ==="
